### ISSUE TITLE
OCA import IndexError: list index out of range 

### ISSUE THREAD

**Issue by flurick** [RxLaboratory/Bluik#28]
I'm getting this error when importing some of my scenes from Krita.

```
Python: Traceback (most recent call last):
  File /app/org.blender.Blender/config/blender/3.3/scripts/addons/bluik/oca.py", line 124, in execute
    self.import_oca(context)
  File /app/org.blender.Blender/config/blender/3.3/scripts/addons/bluik/oca.py", line 150, in import_oca
    self.import_layer(context, layer, scene)
  File "/app/org.blender.Blender/config/blender/3.3/scripts/addons/bluik/oca.py", line 174, in import_layer
    framesShader = layers.create_layer_shader(ocaLayer['name'], ocaLayer['frames'], ocaLayer['animated'], self.shader)
  File "/app/org.blender.Blender/config/blender/3.3/scripts/addons/bluik/layers.py", line 252, in create_layer_shader
    mat, texture_node = dublf.materials.create_image_material(frames[0]['fileName'], layer_name, shader)
IndexError: list index out of range

```

**Comment by Nico-Duduf** [comment]
Hi,
Thanks for the feedback; can you post the OCA folder (zipped with the oca file & all pngs) so I can test with your export? Thanks

**Comment by flurick** [comment]
Thank You, turns out that transform mask gets exported as an empty folder with an other empty folder that is named after the transform mask. So the issues is rather with the export.
